version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      TOKEN_EXPIRATION_MINUTES: ${TOKEN_EXPIRATION_MINUTES}
      DATABASE_SCHEMA_PATH: ${DATABASE_SCHEMA_PATH}
      EMPLOYEES_FILE_PATH: ${EMPLOYEES_FILE_PATH}
      EMPLOYERS_FILE_PATH: ${EMPLOYERS_FILE_PATH}
    depends_on:
      - db
      - redis
    volumes:
      - ./path/to/your/data:/path/to/your/data

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <database>
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
