version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      TOKEN_EXPIRATION_MINUTES: ${TOKEN_EXPIRATION_MINUTES}
      DATABASE_SCHEMA_PATH: ${DATABASE_SCHEMA_PATH}
      EMPLOYEES_FILE_PATH: ${EMPLOYEES_FILE_PATH}
      EMPLOYERS_FILE_PATH: ${EMPLOYERS_FILE_PATH}
    depends_on:
      - db
      - redis
    volumes:
      - ./database_schema.sql:/app/database_schema.sql
      - ./data:/app/data

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
